UVIS update
spacetelescope/astrogrism pull request #4
Opened 2021-08-23 17:31 UTC by rosteen

@duytnguyendtn I wanted this here so I could start working on the unit tests here instead of in sandbox, so I went ahead and did it. Also note that in the interest of having any config files in the same place, I changed the config directory layout to `config/telescope` instead of `telescope/config` (currently it's just HST)

2021-08-23 18:49 UTC, duytnguyendtn requested changes
Found the testing failure. The leading `.` indicated a relative (package) import. Reverting these changes allowed my pytest to pass

2021-08-23 18:49 UTC, duytnguyendtn commented on astrogrism/grism_observation.py
> +from HST.dispersion_models import DISPXY_Extension
```suggestion
from .HST.transform_models import WFC3IRForwardGrismDispersion, \
                                  WFC3IRBackwardGrismDispersion
from .HST.dispersion_models import DISPXY_Extension
```

2021-08-23 18:52 UTC, rosteen commented on astrogrism/grism_observation.py
> +from HST.dispersion_models import DISPXY_Extension
Ahh good call. Thanks!

2021-08-23 19:06 UTC, rosteen commented
Test coverage will be addressed in a follow-up PR

2021-08-23 19:35 UTC, duytnguyendtn commented
Wonderful! Should I review as is @rosteen, or are you planning on adding UVIS tests to this PR (in which case, I'll hold off)?

2021-08-24 16:38 UTC, rosteen commented
Any objection to merging this now that CI is passing?

2021-08-24 19:20 UTC, duytnguyendtn commented
In the midst of a review now. I doubt there will be any issues, so if it's blocking your work, go for it!

2021-08-24 20:10 UTC, duytnguyendtn approved these changes
The UVIS_Testing notebook works as expected with this PR. Merging!

2021-08-24 20:10 UTC, merged